steps:
# destination path = gcr.io/gcp id/fuction:latest

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/single-edition-358307/heart-data_check:latest
  - --cache=true
  - --cache-ttl=10000h
  - --dockerfile=./data_check/Dockerfile

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/single-edition-358307/heart-preprocess:latest
  - --cache=true
  - --cache-ttl=10000h
  - --dockerfile=./preprocess/Dockerfile

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/single-edition-358307/heart-hyperparameter:latest
  - --cache=true
  - --cache-ttl=10000h
  - --dockerfile=./hyperparameter/Dockerfile

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/single-edition-358307/heart-train:latest
  - --cache=true
  - --cache-ttl=10000h
  - --dockerfile=./train/Dockerfile

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/single-edition-358307/heart-test:latest
  - --cache=true
  - --cache-ttl=10000h
  - --dockerfile=./test/Dockerfile

#- name: 'gcr.io/kaniko-project/executor:latest'
#  args:
#  - --destination=gcr.io/single-edition-358307/heart-yatai:latest
#  - --cache=true
#  - --cache-ttl=10000h
#  - --dockerfile=./yatai/Dockerfile


# gcloud builds submit --config cloudbuild.yaml .
